### ISSUE TITLE
execution failed using faraday-0.16.1

### ISSUE THREAD

**Issue by shmokmt** [x-motemen/git-pr-release#34]
TL;DR: When using faraday-0.16.1, execution failed.
Environment: CircleCI(image: circleci/ruby)

Simply installing with `gem install git-pr-release` will now install faraday-0.16.1, but it will stop working.

Therefore, I think that it is necessary to specify the package version in git-pr-release's Gemfile, what do you think?

e.g. `gem "faraday", "x.y.z"`

### log
```
#!/bin/bash -eo pipefail
gem install -N git-pr-release
Fetching faraday-0.16.1.gem
Fetching public_suffix-4.0.1.gem
Fetching multipart-post-2.1.1.gem
Fetching highline-2.0.2.gem
Fetching colorize-0.8.1.gem
Fetching addressable-2.7.0.gem
Fetching octokit-4.14.0.gem
Fetching sawyer-0.8.2.gem
Fetching git-pr-release-0.8.0.gem
Fetching diff-lcs-1.3.gem
Successfully installed multipart-post-2.1.1
Successfully installed faraday-0.16.1
Successfully installed public_suffix-4.0.1
Successfully installed addressable-2.7.0
Successfully installed sawyer-0.8.2
Successfully installed octokit-4.14.0
Successfully installed highline-2.0.2
Successfully installed colorize-0.8.1
Successfully installed diff-lcs-1.3
Successfully installed git-pr-release-0.8.0
10 gems installed
```

```
#!/bin/bash -eo pipefail
git-pr-release --no-fetch
Traceback (most recent call last):
	13: from /usr/local/bundle/bin/git-pr-release:23:in `<main>'
	12: from /usr/local/bundle/bin/git-pr-release:23:in `load'
	11: from /usr/local/bundle/gems/git-pr-release-0.8.0/bin/git-pr-release:11:in `<top (required)>'
	10: from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 9: from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 8: from /usr/local/bundle/gems/octokit-4.14.0/lib/octokit.rb:4:in `<top (required)>'
	 7: from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 6: from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 5: from /usr/local/bundle/gems/octokit-4.14.0/lib/octokit/default.rb:1:in `<top (required)>'
	 4: from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 3: from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 2: from /usr/local/bundle/gems/octokit-4.14.0/lib/octokit/middleware/follow_redirects.rb:9:in `<top (required)>'
	 1: from /usr/local/bundle/gems/octokit-4.14.0/lib/octokit/middleware/follow_redirects.rb:11:in `<module:Octokit>'
/usr/local/bundle/gems/octokit-4.14.0/lib/octokit/middleware/follow_redirects.rb:14:in `<module:Middleware>': superclass must be a Class (Faraday::DeprecatedConstant given) (TypeError)
Exited with code 1
```

**Comment by sh-tech** [comment]
In my environment, it worked correctly with `faraday-0.15.4`.
